import React,{useEffect,useState} from 'react'; import {createRoot} from 'react-dom/client'; import {io} from 'socket.io-client'; import './style.css';
const socket=io(import.meta.env.VITE_SERVER_URL||window.location.origin,{autoConnect:false});
function App(){const [screen,setScreen]=useState('home'),[name,setName]=useState(''),[room,setRoom]=useState(''),[state,setState]=useState(null),[question,setQuestion]=useState(null),[timeLeft,setTimeLeft]=useState(15),[msg,setMsg]=useState(''),[selected,setSelected]=useState(null),[result,setResult]=useState(null),[final,setFinal]=useState(null);
 useEffect(()=>{socket.connect();socket.on('joined',x=>{setRoom(x.code);setScreen('lobby');setMsg('');});socket.on('state',setState);socket.on('question',x=>{setQuestion(x);setTimeLeft(x.time);setSelected(null);setResult(null);setScreen('game');});socket.on('answerResult',setResult);socket.on('roundEnd',()=>setScreen('scores'));socket.on('gameOver',x=>{setFinal(x.scores);setScreen('final');});socket.on('errorMsg',setMsg);return()=>socket.removeAllListeners()},[]);
 useEffect(()=>{if(screen!=='game'||!question)return;const deadline=Date.now()+timeLeft*1000;const timer=setInterval(()=>setTimeLeft(Math.max(0,Math.ceil((deadline-Date.now())/1000))),200);return()=>clearInterval(timer)},[question,screen]);
 const create=()=>{if(!name.trim())return setMsg('Enter your name first.');socket.emit('create',{name})}; const join=()=>{if(!name.trim()||!room.trim())return setMsg('Enter your name and room code.');socket.emit('join',{name,code:room})};
 if(screen==='home')return <main className="center"><div className="card hero"><div className="badge">LIVE • 2–8 PLAYERS</div><h1>Battle <span>Quiz</span></h1><p>Compete in real time. Answer fast. Score more.</p><input placeholder="Your name" maxLength="20" value={name} onChange={e=>setName(e.target.value)}/><button onClick={create}>Create Room</button><div className="or">OR</div><div className="join"><input placeholder="Room code" maxLength="6" value={room} onChange={e=>setRoom(e.target.value.toUpperCase())}/><button className="secondary" onClick={join}>Join</button></div>{msg&&<div className="error">{msg}</div>}<details><summary>How to play</summary><p>Join with a room code. The host starts when at least 2 players are ready. Each round lasts 15 seconds. Correct answers earn points, with more points for faster answers. After 5 rounds, the highest score wins.</p></details></div></main>;
 if(screen==='lobby')return <main className="center"><div className="card"><div className="badge">ROOM</div><div className="code">{room}</div><p>Share this code with the other players.</p><div className="players">{state?.players?.map(p=><div className="player" key={p.id}><span>●</span>{p.name}{p.id===socket.id&&' (you)'}</div>)}</div><button disabled={(state?.players?.length||0)<2} onClick={()=>socket.emit('start')}>Start Game</button>{(state?.players?.length||0)<2&&<small>Waiting for at least one more player…</small>}{msg&&<div className="error">{msg}</div>}</div></main>;
 if(screen==='game')return <main className="game"><header><b>Battle Quiz</b><span>Round {question.round}/{question.total}</span><span>Room {room}</span></header><section className="card question"><div className="timer" aria-live="polite">{timeLeft} SEC</div><h2>{question.q}</h2><div className="answers">{question.answers.map((a,i)=><button key={a} disabled={selected!==null||timeLeft===0} className={selected===i?'chosen':''} onClick={()=>{setSelected(i);socket.emit('answer',{index:i})}}>{a}</button>)}</div>{result&&<div className={result.correct?'good':'bad'}>{result.correct?'Correct!':'Not this time.'}</div>}</section></main>;
 if(screen==='scores')return <main className="center"><div className="card"><div className="badge">ROUND COMPLETE</div><h2>Scores</h2>{[...(state?.players||[])].sort((a,b)=>b.score-a.score).map((p,i)=><div className="score" key={p.id}><span>#{i+1} {p.name}</span><b>{p.score}</b></div>)}<p>Next round starting…</p></div></main>;
 return <main className="center"><div className="card"><div className="badge">GAME OVER</div><h1>Final Results</h1>{final?.map((p,i)=><div className="score" key={p.name}><span>{i===0?'🏆 ':''}{p.name}</span><b>{p.score}</b></div>)}<button onClick={()=>{setFinal(null);setScreen('home');setState(null)}}>Play Again</button></div></main>}
createRoot(document.getElementById('root')).render(<App/>);
